name: test

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  foundry:
    strategy:
      fail-fast: true

    name: Reproduce issue on latest nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-2f4dc6cc514ff816589144622f1d6e183dddb13b

      - name: Forge version
        run:  forge --version

      - name: Show scripts
        run:  ls script

      - name: Run script without --slow (should succeed)
        run:  forge script ./script/BlockHashIssueScript.sol:BlockHashScript -vvvv --fork-url=$FORK_URL --private-key=$PRIVATE_KEY
        env:
          FORK_URL: ${{ secrets.FORK_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}

      - name: Run script with --slow (will fail)
        run:  forge script ./script/BlockHashIssueScript.sol:BlockHashScript -vvvv --fork-url=$FORK_URL --private-key=$PRIVATE_KEY --slow
        env:
          FORK_URL: ${{ secrets.FORK_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}


  last-nightly:
    strategy:
      fail-fast: true

    name: Show absence of issue at given nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-64fe4acc97e6d76551cea7598c201f05ecd65639

      - name: Forge version
        run:  forge --version

      - name: Run script with --slow (should succeed)
        run:  forge script script/BlockHashIssueScript.sol:BlockHashScript -vvvv --fork-url=$FORK_URL --private-key=$PRIVATE_KEY --slow
        env:
          FORK_URL: ${{ secrets.FORK_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}


